version: '2'

services:
  proxy:
    build:
      context: ./proxy
      # Set Proxy
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}

    ports:
      - 8080:8080
    privileged: true
    volumes:
      - /root/work/docker/squid/proxy/proxy_log:/var/log/squid/
